#index:
#    path: /
#    controller: App\Controller\ArticleController::homepage
#    controller: App\Controller\DefaultController::index    change the defaultcontroller to articlecontroller and the method to homepage
